// File generated by FlutterFire CLI / manually configured.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'iOS support is not enabled for this project yet.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for the Web app (Reception/Admin Dashboard).
  ///
  /// App ID: 1:766842057256:web:5b69f696d5a3685723bb1d
  /// Display Name: Dr Baiju's Healthcare Dashboard
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOcIvWynMKDV6XuUHLEzbLMwkK1TYmRQ',
    appId: '1:766842057256:web:5b69f696d5a3685723bb1d',
    messagingSenderId: '766842057256',
    projectId: 'dr-baiju-s-healthcare',
    authDomain: 'dr-baiju-s-healthcare.firebaseapp.com',
    storageBucket: 'dr-baiju-s-healthcare.firebasestorage.app',
    measurementId: 'G-WC4Z6THHHN',
  );

  /// Firebase options for the Android app (Patient Flutter App).
  ///
  /// App ID: 1:766842057256:android:c253d928b455658923bb1d
  /// Package Name: com.drbaijus.healthcare
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhEtcL-ZYnUpiBqpcb95Xkxe_Glf8eP6M',
    appId: '1:766842057256:android:c253d928b455658923bb1d',
    messagingSenderId: '766842057256',
    projectId: 'dr-baiju-s-healthcare',
    storageBucket: 'dr-baiju-s-healthcare.firebasestorage.app',
  );
}
