// Mocks generated by Mockito 5.4.6 from annotations
// in baijus/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i17;
import 'dart:ui' as _i15;

import 'package:baijus/models/appointment_model.dart' as _i9;
import 'package:baijus/models/notification_model.dart' as _i13;
import 'package:baijus/models/queue_model.dart' as _i2;
import 'package:baijus/models/user_model.dart' as _i3;
import 'package:baijus/providers/auth_provider.dart' as _i14;
import 'package:baijus/repositories/appointment_repository.dart' as _i8;
import 'package:baijus/repositories/auth_repository.dart' as _i10;
import 'package:baijus/repositories/notification_repository.dart' as _i12;
import 'package:baijus/repositories/queue_repository.dart' as _i7;
import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:firebase_auth/firebase_auth.dart' as _i11;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQueueModel_0 extends _i1.SmartFake implements _i2.QueueModel {
  _FakeQueueModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_2 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_3 extends _i1.SmartFake implements _i5.Settings {
  _FakeSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_4<T extends Object?> extends _i1.SmartFake
    implements _i5.CollectionReference<T> {
  _FakeCollectionReference_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_5 extends _i1.SmartFake implements _i5.WriteBatch {
  _FakeWriteBatch_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_6 extends _i1.SmartFake
    implements _i5.LoadBundleTask {
  _FakeLoadBundleTask_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_7<T1 extends Object?> extends _i1.SmartFake
    implements _i5.QuerySnapshot<T1> {
  _FakeQuerySnapshot_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_8<T extends Object?> extends _i1.SmartFake
    implements _i5.Query<T> {
  _FakeQuery_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_9<T extends Object?> extends _i1.SmartFake
    implements _i5.DocumentReference<T> {
  _FakeDocumentReference_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_10<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePipelineSource_11 extends _i1.SmartFake
    implements _i5.PipelineSource {
  _FakePipelineSource_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueueRepository extends _i1.Mock implements _i7.QueueRepository {
  MockQueueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.QueueModel?> getLiveQueue(String? doctorId) =>
      (super.noSuchMethod(
            Invocation.method(#getLiveQueue, [doctorId]),
            returnValue: _i6.Future<_i2.QueueModel?>.value(),
          )
          as _i6.Future<_i2.QueueModel?>);

  @override
  _i6.Future<_i2.QueueModel> openDailyQueue(String? doctorId) =>
      (super.noSuchMethod(
            Invocation.method(#openDailyQueue, [doctorId]),
            returnValue: _i6.Future<_i2.QueueModel>.value(
              _FakeQueueModel_0(
                this,
                Invocation.method(#openDailyQueue, [doctorId]),
              ),
            ),
          )
          as _i6.Future<_i2.QueueModel>);

  @override
  _i6.Future<_i2.QueueModel> nextPatient(String? queueId) =>
      (super.noSuchMethod(
            Invocation.method(#nextPatient, [queueId]),
            returnValue: _i6.Future<_i2.QueueModel>.value(
              _FakeQueueModel_0(
                this,
                Invocation.method(#nextPatient, [queueId]),
              ),
            ),
          )
          as _i6.Future<_i2.QueueModel>);

  @override
  _i6.Future<void> addTokenToQueue({
    required String? queueId,
    required Map<String, dynamic>? tokenJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTokenToQueue, [], {
              #queueId: queueId,
              #tokenJson: tokenJson,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AppointmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRepository extends _i1.Mock
    implements _i8.AppointmentRepository {
  MockAppointmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i9.AppointmentModel>> getAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getAppointments, []),
            returnValue: _i6.Future<List<_i9.AppointmentModel>>.value(
              <_i9.AppointmentModel>[],
            ),
          )
          as _i6.Future<List<_i9.AppointmentModel>>);

  @override
  _i6.Future<List<_i9.AppointmentModel>> getAppointmentsByPatientId(
    String? patientId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsByPatientId, [patientId]),
            returnValue: _i6.Future<List<_i9.AppointmentModel>>.value(
              <_i9.AppointmentModel>[],
            ),
          )
          as _i6.Future<List<_i9.AppointmentModel>>);

  @override
  _i6.Future<List<_i9.AppointmentModel>> getAppointmentsByDoctorAndDate({
    required String? doctorId,
    required DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsByDoctorAndDate, [], {
              #doctorId: doctorId,
              #date: date,
            }),
            returnValue: _i6.Future<List<_i9.AppointmentModel>>.value(
              <_i9.AppointmentModel>[],
            ),
          )
          as _i6.Future<List<_i9.AppointmentModel>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> requestOtp(
    String? phoneNumber,
    dynamic Function(String)? codeSent,
    dynamic Function(_i11.FirebaseAuthException)? verificationFailed,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [
              phoneNumber,
              codeSent,
              verificationFailed,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserModel> verifyOtp(String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [otp]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#verifyOtp, [otp])),
            ),
          )
          as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<_i3.UserModel> loginWithEmailPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmailPassword, [email, password]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#loginWithEmailPassword, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.UserModel>);

  @override
  _i6.Future<_i3.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i3.UserModel?>.value(),
          )
          as _i6.Future<_i3.UserModel?>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserModel> login(String? phone, String? dummy) =>
      (super.noSuchMethod(
            Invocation.method(#login, [phone, dummy]),
            returnValue: _i6.Future<_i3.UserModel>.value(
              _FakeUserModel_1(this, Invocation.method(#login, [phone, dummy])),
            ),
          )
          as _i6.Future<_i3.UserModel>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i12.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i13.NotificationModel>> getNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [userId]),
            returnValue: _i6.Future<List<_i13.NotificationModel>>.value(
              <_i13.NotificationModel>[],
            ),
          )
          as _i6.Future<List<_i13.NotificationModel>>);

  @override
  _i6.Stream<List<_i13.NotificationModel>> getNotificationsStream(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsStream, [userId]),
            returnValue: _i6.Stream<List<_i13.NotificationModel>>.empty(),
          )
          as _i6.Stream<List<_i13.NotificationModel>>);

  @override
  _i6.Future<void> markAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createNotification(_i13.NotificationModel? notification) =>
      (super.noSuchMethod(
            Invocation.method(#createNotification, [notification]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i14.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> login(String? phone, String? dummyPassword) =>
      (super.noSuchMethod(
            Invocation.method(#login, [phone, dummyPassword]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> verifyOtp(String? otp) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [otp]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> loginWithEmailPassword(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithEmailPassword, [email, password]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i5.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_2(this, Invocation.getter(#app)),
          )
          as _i4.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i5.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_3(this, Invocation.getter(#settings)),
          )
          as _i5.Settings);

  @override
  set app(_i4.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i5.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i5.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_4<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
          )
          as _i5.CollectionReference<Map<String, dynamic>>);

  @override
  _i5.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_5(this, Invocation.method(#batch, [])),
          )
          as _i5.WriteBatch);

  @override
  _i6.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i5.LoadBundleTask loadBundle(_i17.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_6(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i5.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i5.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i5.GetOptions? options = const _i5.GetOptions(),
    required _i5.FromFirestore<T>? fromFirestore,
    required _i5.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i6.Future<_i5.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_7<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i5.QuerySnapshot<T>>);

  @override
  _i6.Future<_i5.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i5.GetOptions? options = const _i5.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i6.Future<_i5.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_7<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i6.Future<_i5.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_8<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i5.Query<Map<String, dynamic>>);

  @override
  _i6.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i5.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_9<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
          )
          as _i5.DocumentReference<Map<String, dynamic>>);

  @override
  _i6.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i6.Stream<void>.empty(),
          )
          as _i6.Stream<void>);

  @override
  _i6.Future<T> runTransaction<T>(
    _i5.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i16.ifNotNull(
                  _i16.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_10<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i6.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i5.PipelineSource pipeline() =>
      (super.noSuchMethod(
            Invocation.method(#pipeline, []),
            returnValue: _FakePipelineSource_11(
              this,
              Invocation.method(#pipeline, []),
            ),
          )
          as _i5.PipelineSource);

  @override
  _i6.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
